version: '3.8'

services:
  api:
    image: ghcr.io/chaitudevi/cnn_catss_dogs_mlops_bits_05454:latest
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    restart: always
    environment:
      - MODEL_PATH=models/model.pt
